#:schema node_modules/wrangler/config-schema.json
name = "cf-create-worker"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "d387199c-d55a-44d5-b1b2-d6e73a2419da"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://twikoo.r2.ruixinwu.com"

[dev]
port = 5000
